function [] = run(generation, plantIndexGrid, subIndexGrid, unitGrid, varianceHourly)
% Start the simulation where each power plant produces energy that is
% transfered to a substation. Power plants moving the least amount of
% electricty are prioritized to reduce the waste cost of the surge of
% electricty from one source to another. Power plants that send first
% succeed and increase in size (Number of panels in operation). Power plants sending
% later decrease in size. 
 
%% Choose some of multiple visualizations of the simulation: 
plotInteraction = false; %% Plot the interaction between power plants and substations. 
plotActiveSubstations = true; %% Plot 2D matrix showing the substations in activation for each hour. 
plotPanelCount = false; %% Plant the number of panels each plant maintains in operation. 

%% Run the simulation: 
% Vector contianing the hourly combined total amount of electricty sent out
% from each substation. 
energyToGridTotals = zeros(size(generation,3), 1); 

% Run the simulation for each hour of the year. 
    for q = 1:size(generation, 3) 

        % Only consider hours for which the solar panels can reasonabily
        % run and generate electricity. 
        if(generation(1,1,q) ~= 0) 
            % Connect each plant to a substation on an hourly basis. 
            subToPlantOptions = connectPlantsToSub(plantIndexGrid, subIndexGrid, generation(:,:,q), unitGrid); 
            % Transfer electricity from power plants to their substations. 
            [hourGeneration, hourSub, plantsAccessedOrder] = transferPlantsToSub(generation(:,:,q), varianceHourly, plantIndexGrid, subIndexGrid, subToPlantOptions, unitGrid); 
            % Update the number of panels each plant has based on the
            % impact of the order in which the plants are pulled 
            unitGrid = orderImpact(unitGrid, plantsAccessedOrder, plantIndexGrid); 
            % Energy collected by the substations and sent to the grid: 
            energyToGridTotals(q) = transferSubToGrid(hourSub); 

            %% Possible visuals of the simulation: 

            % Visual of the interaction between the amount of electricity
            % generated by the plants and sent to the substations 
            if plotInteraction == true 
                figure(1); 
                bar3(hourGeneration, .9, 'r') 
                hold on 
                bar3(hourSub, .2, 'g') 
                drawnow
                hold off 
            end 

            % Plot the substations that were actively transmitting energy
            % during active hours 
            if plotActiveSubstations == true 
                figure(2); 
                map = [0 0.8 0; 1 1 1]; 
                imagesc(~hourSub) 
                colormap(map) 
                drawnow 
            end 

            % Plot how the amount of panels each plant has through time
            % changes. 
            if plotPanelCount == true 
                figure(3); 
                bar3(unitGrid, 'g')
                drawnow 
            end 
        end 
    end
end 

